### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by hansje69** [anselal/antminer-monitor#106]
When will there be another update? 

by the look of all the requests of which many were going to be in the next update, it seems it is still ## [v0.4.0] - 2018-02-28 which is more than 3 months ago.

Any idea when there will be a v0.5.0 ? or at least a v0.5.0beta ?

Cheers :)

**Comment by anselal** [comment]
Hi there @hansje69,

there will definitely be another release of AntminerMonitor. I now I haven't pushed any new features in the last months due to lack of time. I am preparing a new version with some minor fixes, updated code, new miner support and maybe a login screen..

Please be patient

**Comment by hansje69** [comment]
Will this also include the option to access remotely instead of locally?

Locally it works as a charm with internal network ip’s, but I would love to
access it on my 4G mobile connection and access anywhere I am haha

I remember you said, only after it has built in safety features such as
login panel, so when you mention for next update it has login panel, will
it be able also to access remotely ?

Thanks Anselal! :)

**Comment by anselal** [comment]
To access your AntminerMonitor remotely you have just to config your router, it has nothing to do with my software. 

I just said that it is not safe since there is no login screen. On the other hand since my software do not have any features that can alter your miner's config it is not much of a risk but I totally discourage you to do it since you will expose info to the public.

I think that in the next release there will be a login screen ;)
