### ISSUE TITLE
WARNING high temperatures on  [does not display ip address any more]

### ISSUE THREAD

**Issue by TRingo1** [anselal/antminer-monitor#112]
I have updated to the current version, and the yellow warning does not display the miner ip address anymore.
![image](https://user-images.githubusercontent.com/21029332/42413973-c0fbf1be-81f9-11e8-839d-c90037538bc4.png)

**Comment by anselal** [comment]
Actually you shouldn't get both notifications.
Which version are you on ? The laters master or release 0.4.0 ?

**Comment by TRingo1** [comment]
Running the latest master

**Comment by anselal** [comment]
I think I know where the error is. Will update it tomorrow. Thanks for the feedback

**Comment by anselal** [comment]
I found the error but I don't know why this is happening. As you can see below I split the line because it was too long. No error shows up while running the app but the string appears incomplete.

https://github.com/anselal/antminer-monitor/blob/45236231a09f01394b48f3dd99cd55436d66853a/antminermonitor/blueprints/asicminer/views/antminer.py#L150-L151

I will search why this is happening and fix it. Don't want to have long lines in my code !!

**Comment by anselal** [comment]
For some reason the line continuation does not seem to work. I applied a patch
