### ISSUE TITLE
Hostname instead of IP address

### ISSUE THREAD

**Issue by pes0** [anselal/antminer-monitor#134]
Previous versions allowed to enter hostname in ip address.
now in version 0.5 it must be an ip address.

Please change back to allow hostnames again in IP Address field

My miners are all set to dynamically retrieve IP addresses and are reached by the
hostname inside the lan.

Thank you very much #

**Comment by anselal** [comment]
I added the ip validation for security because adding something invalid
could break the application. You can always remove the validation by
editing the line
https://github.com/anselal/antminer-monitor/blob/b7f75c84ffc0a2883eb2a92a0136bc5d8d9ede37/antminermonitor/blueprints/asicminer/templates/asicminer/home.html#L26

and removing the pattern attribute.

Στις Κυρ, 21 Οκτ 2018, 14:13 ο χρήστης pes0 <notifications@github.com>
έγραψε:
