### ISSUE TITLE
Hash rate not showing up correctly

### ISSUE THREAD

**Issue by anselal** [anselal/antminer-monitor#22]
The cgminer-api returns the hashrate of the miner as "GHS 5s" and I named the cell accordingly to that.
But the hashrates for the L3+ and D3 are actually returned in MH/s.
This error will probably be fixed in the next release

**Comment by gnanet** [comment]
Thank you for noting this.

i also noticed that minerStatus.cgi of antminer D3 is talking about
**MH/S(RT)** and **MH/S(avg)**
**17,139.8** and **17,507.59**

while the api response to **stats command** of cgminer itself says:

> 
> GHS 5s=17139.8,
> GHS av=17507.59,
> 

This was collected from:

> CGMiner=4.9.0,
> Miner=1.0.0.6,
> CompileTime=Thu Aug 31 13:38:33 CST 2017,
> Type=Antminer D3
> 

This is a mis-labeling in the cgminer-api, i think, because [bitmain itself is talking about 15GHS not 15000GHS](https://shop.bitmain.com/productDetail.htm?pid=00020170718203947438V537cuy7067F)

> 1. Specifications of the Antminer D3 are as follows:
> a) Hash rate: 15 GH/s (Variation of ±5% is expected)
>

**Comment by anselal** [comment]
I don't know why no one hasn't noticed it so far, not even me :smile:

**Comment by gnanet** [comment]
interesting to note, i used the miner.php to start up with some summarized status page, and exactly because of this labeling issue no MHS or GHS columns were shown by default, and after i changed some strings from MHS to GHS those columns were shown, but i didnt realize that this was a mis-labeling. Now i went trough the whole source of miner.php, and done some number_format , divided by 1000 etc :D
