### ISSUE TITLE
It will be better to add port parsing for miner's IP address

### ISSUE THREAD

**Issue by garkinv** [anselal/antminer-monitor#29]
Thanks for your app. It's cool!
I need to add miners which are placed on some port, is it possible to handle it?

**Comment by anselal** [comment]
Have you tried adding the miners with just their ip? The app is communicating with miners on a default port other than that of the miner's web interace.

**Comment by garkinv** [comment]
Tried - no luck. I have remote miners and forward ports on router locally to have access from world-wide. so for example I need to open 100.100.100.100:555(public ip) to get access to miner which has 192.168.0.1 IP inside network.

**Comment by anselal** [comment]
That won't work. You are supposed to run the app on the same network as your miners.
Besides that, what you are doing, exposing you miner to the internet is a big security hole.
Again, the app is not connecting to the miner's interface so forwarding a port on your router to port 80 on your miner won't work.
Install the app on a pc or better on a raspberry pi on your internal network and if you want you can forward an external port to port 5000 on your internal network. I don't advice you to do the port forward since my app doesn't have a login screen yet.

**Comment by garkinv** [comment]
Thanks! Suggestion with raspberry pi is good! Will try that, I know that it's security hole...

**Comment by anselal** [comment]
Thank you for using my app !!!
