### ISSUE TITLE
Show an indicator if the temperatures are high.

### ISSUE THREAD

**Issue by sergioclemente** [anselal/antminer-monitor#42]
According to couple of threads in bitcointalk it seems the target temperatures should be below 70-75. We should indicate in the ui

I will be happy to do this once we figure it out how to expose.

**Comment by anselal** [comment]
This is already implemented. If the temp is too high the table row of the miner turns red and an notification shows up above the table.

**Comment by sergioclemente** [comment]
Found it. Are you ok with me making it a settings? I saw some folks saying the recommended temp is somewhere below 70-75.

**Comment by anselal** [comment]
I set the temperature to 80 because many users own D3s and the temperature of those machines if around 80 degrees. This is because of the over-overclocked machines bitmain sold. I think 80 is a good point to notify the user. 70 is a normal temperature if you compare it with a CPU.
A L3+ and S7 is about 50-55 degrees and a S9 is around 75 degrees. Those values are for miners with the default frequency set.

**Comment by anselal** [comment]
What do you mean be "making it a setting" ? To create a settings.py file and add the value there ?
Actually I wanted to create an admin panel and add those values to the database in the `settings` table

**Comment by alaaelmahdy** [comment]
for S9 please consider the alert after 85 degrees as it works fine till 90's and stop mining at 110's for L3 65 is the Alert zone as it works fine till 70 and will stop mining at 90

**Comment by anselal** [comment]
@alaaelmahdy exactly my thought but for the L3+ I think 70+ degrees is preferred alert  zone
