### ISSUE TITLE
HW error rate

### ISSUE THREAD

**Issue by adstek** [anselal/antminer-monitor#52]
The HW error rate says 0% on all miners, is there an easy fix?

**Comment by anselal** [comment]
You should be happy about it. This means your miner has no Hardware Errors.

**Comment by adstek** [comment]
The miners says otherwise

**Comment by anselal** [comment]
The field in the table show the HW error rate. It is a percentage. You shouldn't worry about the HW errors itself because they don't indicate anything by them self. You should worry about the percentage. But in your case it is zero so don't worry.
In the miner's web interface the actual HW Error Rate is shown under `DiffA#`. Take a look at my screenshot. I have 9 HW errors but the HW error rate is zero ;)
I hope this helped !!!!

![2018-01-12_11h32_11](https://user-images.githubusercontent.com/8732668/34868561-e4eb05f8-f78c-11e7-89d6-4e3e5cc98fc0.png)

![2018-01-12_11h35_08](https://user-images.githubusercontent.com/8732668/34868573-edb5cbb4-f78c-11e7-8563-3efab960d979.png)

**Comment by adstek** [comment]
Oh, on my L3+ I have a row called Nonce# that says 1.9416%, but the row under DiffR# says 0.0079% I thought it was the Nonce# that displayed HW... Do you know what Nonce is then 😂?

**Comment by anselal** [comment]
This is my L3+

![2018-01-12_12h06_00](https://user-images.githubusercontent.com/8732668/34869897-1de6eddc-f791-11e7-8859-aa3705f6e486.png)

If you want to calculate the HW Error Rate yourself the formula is `HW / (diffA + diffR + HW) * 100`.

From https://en.wikipedia.org/wiki/Cryptographic_nonce
> In cryptography, a nonce is an arbitrary number that can only be used once.

I think we are out of topic now !!!

**Comment by adstek** [comment]
Thanks! 😊
