### ISSUE TITLE
Add A3 miner

### ISSUE THREAD

**Issue by starrateit** [anselal/antminer-monitor#59]
Hi,

Thanks for the help once I loaded the latest version works like a charm.
Really like it clean and simple.

Is there any chance you can look at adding in the new Antminer A3, I have added it using L3+ for now but it throws up an error about the chips still monitors though for now.

Thanks, 

Spencer

**Comment by sergioclemente** [comment]
Hello. Thanks for using the app.

It should be pretty simple to add support for the A3. Do you mind sharing the output of:

http://127.0.0.1:5000/<miner_ip>/pools
http://127.0.0.1:5000/<miner_ip>/stats

Making sure you replace <miner_ip> for the A3 ip. And assuming you are running locally.

That will contain information about the miner which might make the porting a lot easier.

**Comment by brmcc** [comment]
I was able to use the D3 profile and it worked perfectly for the A3, the only difference is it reports in MH/s instead of GH/s which is what the miner is actually doing.

**Comment by anselal** [comment]
@brmcc thank you for the feedback. This means that the have the same number of chips and boards. I will add the A3 in the next days with some other changes i made 😉

**Comment by starrateit** [comment]
Awesome, I am currently running 2 x A3’s as L3+ and they are complaining but it still gives me vital stats. Will give the dash miners a go instead until the dev is complete. Look below in screen shot how the show.

Are you guys all running under 80 degree’s on your chips, this is a challenge to achieve in our environment. I am in durban, South Africa, we currently have a 5000CFM exhaust fan on our exhaust hot room, and sometimes are hitting 99 degree’s on our Centre board chips for few hours which I know is not ideal when our temps get high.
We will be upgrading this exhaust to a 8000CFM exhaust fan and adding in a Air intake fan around 9000CFM+ to give a positive pressure, hoping to drop our temps under 80, but quite a challenge when you ambient is around 30 degree’s.

Let me know if you think we doing damage running over 70.
Below is our 22 miners in this mining room.

[Image]


Temp’s in our mining room are sitting at 30 degree’s and it is 7pm. Lol. They actually pretty constant around this temp, until the ambient gets very hot. We have upgraded our insulation between our exhaust room and mining room and haven’t had anything over 90 degree’s since then.
[Image]


Our exhaust room is at 48 degree’s right now, this is behind our miners where dumping all he hot air into.

[Image]

How you keeping your miners cool?

Any how have a good weekend looking forward to your updates.

Cheers,
Spencer

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by anselal** [comment]
Should have seen that the specs at bitmain's site mention the number of chips and boards on the A3. Sorry for the delay guys.

https://shop.bitmain.com/productDetail.htm?pid=00020180116164357365a2ljX8gx06D3

**Comment by brmcc** [comment]
Hey anselai, thanks for the add!!  I honestly though this project had been abandonded since I hadn;t seen any activity on it in awhile until recently. I'm sending a donation right now as this project has been great for me.

I'm not a programmer by any means but I've hacked mine up enough to show me cabinet temperature from a TempER sensor, and power stats from a Neurio.  I just have shell scripts get that info for me, then put it a file that antminer-monitor prints out with the rest of the info.

I wish I could see your pictures starrateit, but they don't show up!  Sounds like you have a really nice setup. I have a small operation (12 miners) and keep all of mine in a cabinet.  I have a 2000CFM blower in the top  with a motorized damper that will redirect the air outside or inside to keep the rest of the building warm.  It has been near 0 degrees celsius here in the winter a lot so it works out pretty well for the time being anyway.  My exhaust temp is usually around 40-42 degrees C, so I can see your room being that warm!

My A3 is definitely not running in the 80s!  I've had mine reach 100 on occasion but am trying to keep it below that.  I have mine slightly overclocked too and it will give lots of errors if it higher than that being overclocked.  I know the S9s supposedly can go up to 115 degrees before shutting down.  I try not to let mine go over 102 (my high limit temp alarm is 103) or so, but I've had some of them in the upper 90s for months and they all seem to do ok.  

With the L3s that only show board temp I know you're not supposed to go over 80, but on the A3 I'm hoping the chip temp can be about the same as the A9.  So far mine has been ok running below 100 with a little overclock. I guess we will just have to see, I don't think anyone really has any good answers yet.  I can't find anything from bitmain. I hope they put an overtemp shutdown in the software at least!

**Comment by starrateit** [comment]
Hi,
Trying to use the latest create_db.py.
How to do I append to the existing DB or drop the old DB and then re-create?
Would be better to keep existing miners already loaded and just have to append, so I don't have to recapture all miners?
I am getting this
sudo python create_db.py
[INFO] Database already exists.
Thanks,
Spencer

**Comment by anselal** [comment]
@starrateit you can use the new update_db.py script 😉 
More i fo i the README.md file !!!
