### ISSUE TITLE
Auto Ip Scanner

### ISSUE THREAD

**Issue by babycicak** [anselal/antminer-monitor#7]
hi bro, i want to request auto ip scanner for this program. It's useful if you running a big farm, just one button can auto add in all the model sort by ip.

**Comment by anselal** [comment]
I have implemented a function which autodetects the miner type in a range of IP addresses and add them to the database but haven't create the UI yet.

I have tested it and it works great with known miner models.
So far the output of the function is only visible in the console. Will have to find a way to print it in some king of modal window.

Of course it would be much easier and quicker to define the IP range and the model instead of doing auto-detection.

Hopefully this will be a nice feature in the next release.
