### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by danny890** [anselal/antminer-monitor#71]
Is there a way to password protect the miner status page So i can access it external?

**Comment by anselal** [comment]
Sure @danny890, we will add a login screen in the next releases ;)

**Comment by danny890** [comment]
That would be awsome!

**Comment by shotaatosh** [comment]
this will be great!

**Comment by hansje69** [comment]
Great indeed, to some a few things up what I would love to see and is scheduled for a future update:

- Login Access (prevent easy remote access, although I managed to do that already with a simple .htaccess file, reference: http://www.htaccesstools.com/htpasswd-generator/

- Remote Access from external ip’s (if my dedicated Ubuntu server runs the python script, I can’t access the antminermonitor from the www on other computers outside the network)

- Addition to give each miner a port, this way can add 2 miners on same ip but different port

Ofcourse there are so many other requests and things to be planned and implemented, just mentioning that In glad with these 3 things, and everything else I consider a nice bonus feature :)

Any ETA @Anselal ? :)

Note: if stuck on python3 (a simple solution would be to have the script modified into for example python3 -m http.server --bind 127.0.0.1 8000) for remote access, python2 is different though, so I would recommend people to use python3 instead of python2)

**Comment by danny890** [comment]
I also run a Ubuntu server..
I can access the page from an external ip

**Comment by danny890** [comment]
Btw thanks for the htaccess page.
Im going to use that till the project is updated!

@anselal bought you a beer for the great work!

**Comment by anselal** [comment]
@danny890 thank you very much for the support, I really appreciate it. Was your transaction the one from 27/2 using BTC ? I ask because I  log my donations

**Comment by danny890** [comment]
https://blockchain.info/tx/f62e08cc451204d47695378022827a9f5125d9c35f80a6a39d9d2838875c451d

**Comment by brmcc** [comment]
I know this is sort of an old thread now but can anyone tell me where to put the files since the monitor has it's own built in http server?

**Comment by anselal** [comment]
@brmcc Login screen will be part of the next release so please stay tuned !!!
