### ISSUE TITLE
V9 Wrong hashrate Unit

### ISSUE THREAD

**Issue by jvalentinero** [anselal/antminer-monitor#90]
THE V9 SHOWS MY SPEED AS PH/S, NOT TH/S. 
AND TEMPERATURE IS OFF BY 20 DEGREES - SHOWING 70 WHEN IT'S AT 50 IN THE ANTMINER SCREEN.

**Comment by anselal** [comment]
Showing PH/s instead of TH/s is probably a configuration error. Try to update line 

https://github.com/anselal/antminer-monitor/blob/498edf9265ae129bd2d038ed3ce88d01d1a3f269/app/views/antminer.py#L44

and change TH/s to GH/s and let me know if that fixed your issue so I can apply a patch.

About the temperatures I am not sure why that happens in your case. Can you attache here a screenshot of the status page of your miner and a screenshot of the app ? Plus, Please go to your browser at http://localhost:5000/MINER_IP/stats and paste the output here as well (where miner_ip the IP of your miner).

**Comment by anselal** [comment]
Unfortunately no attached files here. Please drag n drop them here

**Comment by jvalentinero** [comment]
there you go partner. thanks for looking at it.

**Comment by anselal** [comment]
I was sure this was causing the confusion. I am displaying the CHIP temp but the status page of your miner only shows the PCB (board temperature), so there is nothing to fix here ;)

I will only have to fix the hashrate unit !!! Sorry for that..

**Comment by jvalentinero** [comment]
Bitmain says there are no other chips. 
I did research – if you  subtract 25 from the 3 chip temperatures for the v9, it will match all three of the chips.


Thank You

Joseph Valenti
Lascivio Est Res

Direct Tel. (914) 309 - 7718
E-mail: Jvalenti@nerolarp.com
http://NeroLarpOnline.com - Member DB
http://NeroLarp.com - NERO Resource site
